/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package passwordmanager.gui;

/**
 *
 * @author Dominik
 */
public class GUIBuilderFrame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public GUIBuilderFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jMenu3 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jToolBar2 = new javax.swing.JToolBar();
        buttonPassworteintragErstellen = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        buttonKategorieErstellen = new javax.swing.JButton();
        splitPane = new javax.swing.JSplitPane();
        leftScrollPane = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        rightScrollPane = new javax.swing.JScrollPane();
        rightCenterPanel = new javax.swing.JPanel();
        passwordLabel = new javax.swing.JPanel();
        pathBar = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        passwordField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuProfil = new javax.swing.JMenu();
        menuProfilErstellen = new javax.swing.JMenuItem();
        menuProfilOeffnen = new javax.swing.JMenuItem();
        menuSpeichern = new javax.swing.JMenuItem();
        menuSpeichernUnter = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuMasterkeyAendern = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuPassworteintragErstellen = new javax.swing.JMenuItem();
        menuKategorieErstellen = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuBeenden = new javax.swing.JMenuItem();
        menuAnsicht = new javax.swing.JMenu();
        menuExtras = new javax.swing.JMenu();
        menuHilfe = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        jLabel1.setText("jLabel1");

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar2.setRollover(true);

        buttonPassworteintragErstellen.setText("Passworteintrag Erstellen");
        buttonPassworteintragErstellen.setFocusable(false);
        buttonPassworteintragErstellen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonPassworteintragErstellen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(buttonPassworteintragErstellen);
        jToolBar2.add(jSeparator4);

        buttonKategorieErstellen.setText("Kategorie Erstellen");
        buttonKategorieErstellen.setFocusable(false);
        buttonKategorieErstellen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonKategorieErstellen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(buttonKategorieErstellen);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("BSP Profil");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Eintrag1");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Eintrag2");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Eintrag3");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Kategorie1");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Eintrag1.1");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Eintrag1.2");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Kategorie2");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Eintrag2.1");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Eintrag2.2");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Eintrag2.3");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Kategorie2.1");
        javax.swing.tree.DefaultMutableTreeNode treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Eintrag2.1.1");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Eintrag2.1.2");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Kategorie3");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Kategorie3.1");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Eintrag3.1.1");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Kategorie3.2");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Eintrag3.2.1");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.setAutoscrolls(true);
        jTree1.setPreferredSize(new java.awt.Dimension(150, 200));
        leftScrollPane.setViewportView(jTree1);

        splitPane.setLeftComponent(leftScrollPane);

        rightCenterPanel.setBackground(new java.awt.Color(250, 50, 50));
        rightCenterPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        rightCenterPanel.setLayout(new java.awt.BorderLayout());

        passwordLabel.setLayout(new java.awt.GridBagLayout());

        pathBar.setText(" Profil:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 38);
        passwordLabel.add(pathBar, gridBagConstraints);

        label1.setText("Passwort:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 16);
        passwordLabel.add(label1, gridBagConstraints);

        passwordField.setText("******");
        passwordField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        passwordLabel.add(passwordField, gridBagConstraints);

        jLabel2.setText("Beschreibung:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        passwordLabel.add(jLabel2, gridBagConstraints);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        passwordLabel.add(jScrollPane1, gridBagConstraints);

        jButton1.setText("Ändern");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        passwordLabel.add(jButton1, gridBagConstraints);

        jButton2.setText("Absenden");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        passwordLabel.add(jButton2, gridBagConstraints);

        rightCenterPanel.add(passwordLabel, java.awt.BorderLayout.PAGE_START);

        rightScrollPane.setViewportView(rightCenterPanel);

        splitPane.setRightComponent(rightScrollPane);

        menuProfil.setText("Profil");

        menuProfilErstellen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menuProfilErstellen.setText("Profil Erstellen");
        menuProfilErstellen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProfilErstellenActionPerformed(evt);
            }
        });
        menuProfil.add(menuProfilErstellen);

        menuProfilOeffnen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuProfilOeffnen.setText("Profil Öffnen");
        menuProfilOeffnen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProfilOeffnenActionPerformed(evt);
            }
        });
        menuProfil.add(menuProfilOeffnen);

        menuSpeichern.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuSpeichern.setText("Speichern");
        menuProfil.add(menuSpeichern);

        menuSpeichernUnter.setText("Speichern unter...");
        menuSpeichernUnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSpeichernUnterActionPerformed(evt);
            }
        });
        menuProfil.add(menuSpeichernUnter);
        menuProfil.add(jSeparator1);

        menuMasterkeyAendern.setText("Masterkey Ändern");
        menuProfil.add(menuMasterkeyAendern);
        menuProfil.add(jSeparator2);

        menuPassworteintragErstellen.setText("Passworteintrag Erstellen");
        menuProfil.add(menuPassworteintragErstellen);

        menuKategorieErstellen.setText("Kategorie Erstellen");
        menuKategorieErstellen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKategorieErstellenActionPerformed(evt);
            }
        });
        menuProfil.add(menuKategorieErstellen);
        menuProfil.add(jSeparator3);

        menuBeenden.setText("Beenden");
        menuProfil.add(menuBeenden);

        menuBar.add(menuProfil);

        menuAnsicht.setText("Ansicht");
        menuBar.add(menuAnsicht);

        menuExtras.setText("Extras");
        menuBar.add(menuExtras);

        menuHilfe.setText("Hilfe");
        menuBar.add(menuHilfe);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
            .addComponent(splitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuProfilErstellenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProfilErstellenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuProfilErstellenActionPerformed

    private void menuProfilOeffnenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProfilOeffnenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuProfilOeffnenActionPerformed

    private void menuSpeichernUnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSpeichernUnterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuSpeichernUnterActionPerformed

    private void menuKategorieErstellenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKategorieErstellenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuKategorieErstellenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIBuilderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIBuilderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIBuilderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIBuilderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIBuilderFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonKategorieErstellen;
    private javax.swing.JButton buttonPassworteintragErstellen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JTree jTree1;
    private javax.swing.JLabel label1;
    private javax.swing.JScrollPane leftScrollPane;
    private javax.swing.JMenu menuAnsicht;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuBeenden;
    private javax.swing.JMenu menuExtras;
    private javax.swing.JMenu menuHilfe;
    private javax.swing.JMenuItem menuKategorieErstellen;
    private javax.swing.JMenuItem menuMasterkeyAendern;
    private javax.swing.JMenuItem menuPassworteintragErstellen;
    private javax.swing.JMenu menuProfil;
    private javax.swing.JMenuItem menuProfilErstellen;
    private javax.swing.JMenuItem menuProfilOeffnen;
    private javax.swing.JMenuItem menuSpeichern;
    private javax.swing.JMenuItem menuSpeichernUnter;
    private javax.swing.JTextField passwordField;
    private javax.swing.JPanel passwordLabel;
    private javax.swing.JLabel pathBar;
    private javax.swing.JPanel rightCenterPanel;
    private javax.swing.JScrollPane rightScrollPane;
    private javax.swing.JSplitPane splitPane;
    // End of variables declaration//GEN-END:variables
}
